### ISSUE TITLE
Implement image validation in backend

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/nachet-backend#57]
## Issue description
The system doesn't validate that actual images are uploaded to the blob storage. Nachet Interactive should only accept user images when using this feature (image upload). 

#### Steps to Reproduce
1. Upload an image
1. The image is uploaded to the cache
1. Test the image to validate it's an actual image

#### Expected Behavior
The system should notify the users if the image they try to upload does not satisfy the validation.

#### Current Behavior
The system does not notify the users if the image is not an image.

#### Possible Solution
Test the image with two checks:
* Test if the object is resizable
* Implement a size check
* Validate extension (PNG, JPEG, JPG, TIFF)
* Validate file header

#### Tasks
- [x] Add an image validation function in the backend
- [x] Implement extension validation check
- [x] Implement resizable validation check
- [x] Implement size validation check
- [x] Implement file header validation check

**Comment by rngadam** [comment]
What about size?

You can also validate the actual headers of files: https://github.com/ahupp/python-magic

**Comment by MaxenceGui** [comment]
> What about size?

Got merged with resizable in my mind. Will add it to the issue

> You can also validate the actual headers of files: https://github.com/ahupp/python-magic

Good idea! In inference_request we already divide files from headers, we can incorporate a check there
