### ISSUE TITLE
Create  the pipeline insertion module

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/nachet-backend#60]
## Issue Description

To help the data scientist to build and push pipelines and models to the blob storage a script was drafted to create this functionality.
However, it is not complete and does not reflect code standards. A complete refactoring is needed to give a more complete tool to help our data scientists.

### Work to do

Create a command line application to upload the JSON file containing the pipeline and the models to the Blob Storage. Version one should be simple and ask the user the path of the document to insert in the blob storage.

### Acceptance Criteria

- The pipeline insertion module asks for the path of the JSON file
- It correctly crypts sensible data before uploading it to the blob storage
- Documentation is clear and complete on how to use the module and insert pipelines into the blob storage

### Tasks

- [x] Create a command line interface script that asks for the JSON path
- [x] Validate that the file is a JSON and contains models and pipelines
- [x] Create a function to crypt sensible data. *That encrypting needs to be decrypted by the backend when retrieving the pipelines and models information*
- [x] Create a pipeline insertion function that notifies the users of any errors or success
- [x] document the usage of the module
- [x] Check that a default pipeline is set by the user
  - https://github.com/ai-cfia/nachet-frontend/issues/111

**Comment by rngadam** [comment]
Given ai-cfia/nachet-frontend#111, also a check to validate that at least one model has default = true ?

**Comment by MaxenceGui** [comment]
> Given [ai-cfia/nachet-frontend#111](https://github.com/ai-cfia/nachet-frontend/issues/111), also a check to validate that at least one model has default = true ?

My plan was to add a `default` key to the pipeline_template.yaml and allow the user (data scientist) to decide which pipeline is the default pipeline. Adding the key means I will need to add it to the Pydantic validation.

But for sure, I will add a check to validate that one of the inserted pipeline is the default one.
