### ISSUE TITLE
Implement API route for picture batch import

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/nachet-backend#74]
### Description :rocket:
```mermaid
sequenceDiagram;  autonumber
  actor User
  participant Frontend
  participant Backend
  participant Datastore

    User ->>+Frontend: Upload session request
    Frontend->>+Backend: HTTP Post Req.
    Backend->>+Datastore: get_all_seeds_names(cursor)
    Datastore-->>-Backend: seed_names res.
    Backend->>+Datastore: is_user_registered(cursor, email)
    Datastore-->>-Backend: user_id res.
    Backend-->>-Frontend: seedNames res.
    Frontend -->>-User: Show session form
    User -) User: Fill form :<br> Seed selection, nb Seeds/Pic, Zoom
    User -)+Frontend: Upload: session folder
    Frontend ->>+Backend: Upload from trusted user request: <br> Seed info, nbSeeds/Pic, Zoom ,<br> Session Folder & User
    Backend -)Datastore: upload_picture_set (cursor, pictures, user_id, <br> seed_name, zoom_level, nb_seeds)
    Note over User, Datastore: Refer to the graph from issue 75 for the rest of the diagram
```

With collaborative effort from the Frontend and the datastore, Nachet Backend needs to implement a new route to allow our users to import a folder of images. The new route must be able to scale with the latest change to the **upload picture from trusted user** functionality and be able to work with a large payload that might exceed the `Quart ` maximum content length. 

### Acceptance Criteria ✅

- The route can upload a payload bigger than the server's maximum content length
- The frontend can recover the data to build their component and the form

### Tasks 🛠️ 

- [ ] Create the bacth import tests
- [ ] Create the batch import route
- [ ] Create the  connexe route to send the frontend the data to collect the right metadata

### Additional Context 📌

Related issue:
* https://github.com/ai-cfia/ailab-db/issues/75
*  https://github.com/ai-cfia/nachet-frontend/issues/127
*  https://github.com/ai-cfia/nachet-datastore/issues/20

**Comment by MaxenceGui** [comment]
### Issue status update

See update on the [pull request](https://github.com/ai-cfia/nachet-backend/pull/75#issuecomment-2077639361)
